console.log("Hi this is my first console screen");
            var firstname="Anushree";
            console.log(firstname);
            var lastname="Upadhyay";
            console.log(lastname);
          var fullname= firstname.concat(lastname);
          console.log(fullname);
          var lengthfullname =fullname.length;
          console.log(lengthfullname);
          var name1="I am Anushree Upadhyay";
          console.log(name1);
          var replacename=name1.replace("I","Myself");
          console.log(replacename);
           var fullname= firstname.concat(lastname);
          console.log(fullname);
          var capitalname="ANUSHREE";
          var number1=15;
          var number2=5;
          console.log(number1+number2);
          var number1=15;
          var number2=5;
          console.log(number1-number2);
          var number1=15;
          var number2=5;
          console.log(number1*number2);
          var number1=15;
          var number2=5;
          console.log(number1/number2);